### ISSUE TITLE
[Error] 'Found circular dependency' when specifying the 'altera_mf' library

### ISSUE THREAD

**Issue by pidgeon777** [VHDL-LS/rust_hdl#124]
My VHDL entity code:

```vhdl
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY altera_mf;
USE altera_mf.all; <- ERROR: Found circular dependency

ENTITY dpram_128word_16bit IS
...
```

My `vhdl_ls.toml` file:

```toml
[libraries]
altera_mf.files = [
  'C:/Aldec/Active-HDL-11.1-x64/vlib/intel_fpgastd/vhdl/altera_mf/src/altera_mf.vhd'
]
work.files = [
  '**/*.vhd'
]
```

Error generated when using the LSP:

`Found circular dependency`

How could this be solved?

**Comment by pidgeon777** [comment]
I solved the problem by specifying the `altera_mf_components.vhd` source file instead of the `altera_mf.vhd` one:

```toml
[libraries]
altera_mf.files = [
  'C:/Aldec/Active-HDL-11.1-x64/vlib/intel_fpgastd/vhdl/altera_mf/src/altera_mf.vhd'
]
```
