### ISSUE TITLE
[Question] How to define multiple distinct projects in the same worksapce root?

### ISSUE THREAD

**Issue by Nabav** [VHDL-LS/rust_hdl#190]
In the workspace root directory, I have two different VHDL projects. Some source file names are the same, but with different contents. Both projects are using the same library name `work` for instantiating modules.

Is it possible to define different projects in one `vhdl_ls.toml` file, each of them with such a definition?

```toml
[libraries]

work.files = [
  '**/*.vhd',
]
```
